ALTER TABLE users ADD COLUMN IF NOT EXISTS college_id UUID;
ALTER TABLE templates ADD COLUMN IF NOT EXISTS category VARCHAR(255);
ALTER TABLE templates ADD COLUMN IF NOT EXISTS difficulty VARCHAR(255);
ALTER TABLE question_bank ADD COLUMN IF NOT EXISTS topic VARCHAR(255);
ALTER TABLE question_bank ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
